# -*- coding: utf-8 -*-
"""streamlit__Afiq

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frUPUGW0cRSCr8ywB1ivprYAU_ULYbzR
"""

!pip install streamlit

import streamlit as st
import joblib
import numpy as np

data = joblib.load('oop_Afiq.pkl')

def main():
  st.title('Mid Term Model Deployment')

  CreditScore = st.slider('Credit Score', min_value = 0.0, max_value = 444.0, value = 0.01)
  Geography = st.selectbox('Geography', ('0', '1', '2')) # 0 = France, 1 = Germany, 2 = Spain
  Gender = st.selectbox('Gender', ('1', '2')) # 1 = male, 2 = female
  Age = st.slider('Age', min_value = 0.0, max_value = 200.0, value = 0.01)
  Tenure = st.slider('Tenure', min_value = 0.0, max_value = 10.0, value = 0.01)
  Balance = st.slider('Balance', min_value = 0.0, max_value = 11409.00, value = 0.01)
  Products = st.selectbox('NumOfProducts', ('1', '2', '3', '4'))
  CC = st.selectbox('HasCrCard', ('1', '0'))
  ActiveMember = st.selectbox('IsActiveMember', ('1', '0'))
  Salary = st.slider('EstimatedSalary', min_value = 0.00, max_value = 20840.00, value = 0.01)
  Churn = st.selectbox('churn', ('1', '0'))



  if st.button('Make Prediction'):
        features = [CreditScore, Geography, Gender, Age, Tenure, Balance, Products, CC, ActiveMember, Salary, Churn]
        result = make_prediction(features)
        st.success(f'The prediction is: {result}')

def make_prediction(features):
    input_array = np.array(features).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

if __name__ == '__main__':
    main()